const C=document.getElementById('world'),X=C.getContext('2d');
let W=1000,H=700,running=false,speed=1,last=performance.now(),acc=0,selected=null,tab='history';
const R=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.floor(Math.random()*a.length)],clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const names=['Mara','Eli','June','Caleb','Nora','Theo','Iris','Jonah','Mae','Rowan','Ada','Silas'];
const roles=['Forager','Maker','Healer','Scout','Cook','Gatherer','Farmer','Builder','Healer','Hunter','Maker','Organizer'];
const traits=['cooperative','cautious','empathetic','bold','practical','curious','stubborn','calm','social','competitive','inventive','organized'];
const BUILD={
 hearth:{n:'Hearth',c:{wood:3,stone:4},b:'fire',w:18,h:18},lean:{n:'Lean-to',c:{wood:8},b:'beds',w:30,h:22},rack:{n:'Drying rack',c:{wood:7},b:'preserve',w:24,h:14},hut:{n:'Wattle hut',c:{wood:16,thatch:10},b:'housing',w:36,h:30,k:'wattle'},store:{n:'Raised storehouse',c:{wood:20,thatch:8},b:'storage',w:38,h:28,k:'storage'},farm:{n:'Field',c:{wood:5},b:'farm',w:58,h:42,k:'cultivation'},well:{n:'Lined well',c:{wood:8,stone:18},b:'well',w:28,h:28,k:'masonry'},shop:{n:'Tool workshop',c:{wood:18,stone:10},b:'craft',w:42,h:32,k:'specialists'},hall:{n:'Meeting hall',c:{wood:30,stone:14,thatch:16},b:'governance',w:58,h:42,k:'council'},shrine:{n:'Ancestor shrine',c:{wood:8,stone:14},b:'ritual',w:28,h:26,k:'ritual'},wall:{n:'Palisade',c:{wood:24},b:'defense',w:72,h:9,k:'defense'}};
const EXPERIMENTS=[
 {id:'wattle',name:'Wattle & daub',needs:['wood','thatch'],chance:.14,desc:'woven walls sealed with earth'},
 {id:'storage',name:'Food storage',needs:['food','wood'],chance:.13,desc:'raised dry storage and preservation'},
 {id:'cultivation',name:'Cultivation',needs:['food','water'],chance:.11,desc:'deliberately tending useful plants'},
 {id:'masonry',name:'Stone lining',needs:['stone','water'],chance:.10,desc:'fitting stone to strengthen pits and wells'},
 {id:'specialists',name:'Craft specialization',needs:['wood','stone'],chance:.08,desc:'dedicated work areas and repeated craft'},
 {id:'council',name:'Council tradition',needs:[],chance:.07,desc:'formal communal decisions'},
 {id:'ritual',name:'Ancestor ritual',needs:[],chance:.065,desc:'shared remembrance of the dead'},
 {id:'defense',name:'Fortification',needs:['wood'],chance:.055,desc:'organized perimeter defense'}
];
const customIdeas=[
 {name:'Smokehouse',purpose:'preserve hunted meat',materials:{wood:12,stone:5,thatch:5},primitives:['walls','roof','hearth','drying_beams'],benefit:'preserve'},
 {name:'Storage pit',purpose:'protect dry food',materials:{wood:4,stone:8},primitives:['pit','cover'],benefit:'storage'},
 {name:'Fish weir',purpose:'capture river fish',materials:{wood:14,stone:5},primitives:['posts','fence'],benefit:'fish'},
 {name:'Animal pen',purpose:'hold captured animals',materials:{wood:18},primitives:['posts','fence'],benefit:'animals'},
 {name:'Communal oven',purpose:'cook efficiently',materials:{stone:16,wood:6},primitives:['hearth','walls'],benefit:'cooking'},
 {name:'Watch platform',purpose:'see danger earlier',materials:{wood:20},primitives:['posts','platform'],benefit:'defense'}
];
let S;
function person(i,name=names[i%names.length]){return{id:i,name,role:roles[i%roles.length],trait:traits[i%traits.length],age:Math.floor(R(18,44)),parents:[],children:[],partner:null,x:510+R(-45,45),y:350+R(-40,40),tx:510,ty:350,alive:true,health:100,hunger:R(5,15),thirst:R(4,13),fatigue:R(5,18),morale:R(68,90),social:R(10,35),task:'looking around',until:0,cool:R(0,15),res:null,proposal:null,build:null,site:null,carry:null,known:{river:false,food:false,wood:false,stone:false,game:false,thatch:false},mem:['We entered this valley together.'],beliefs:[],trust:{},skill:{gather:R(.75,1.3),build:R(.7,1.3),heal:R(.65,1.25),think:R(.75,1.3)},goal:pick(['keep everyone alive','make a permanent home','be remembered','learn the valley','feed the group','make better tools','protect the next generation'])}}
function linkTrust(){for(const a of S.people)for(const b of S.people)if(a.trust[b.id]==null)a.trust[b.id]=a.id===b.id?100:R(45,68)}
function init(){S={day:1,min:420,temp:71,weather:'Clear',store:{food:13,water:15,wood:8,stone:2,thatch:5},knowledge:0,camp:{x:510,y:350},people:Array.from({length:12},(_,i)=>person(i)),buildings:[],events:[{t:'D1 07:00',text:'Twelve hunter-gatherers enter an unfamiliar valley.',cls:''}],speech:[],observations:['The valley contains resources the band has not mapped yet.'],institutions:[],traditions:[],tech:{fire:true,stone_tools:true},nextBuilding:1,nextPerson:12,resources:[{id:'river',type:'water',x:155,y:170,q:9999,known:false},{id:'food',type:'food',x:800,y:170,q:110,known:false},{id:'wood',type:'wood',x:230,y:555,q:260,known:false},{id:'stone',type:'stone',x:760,y:555,q:240,known:false},{id:'game',type:'food',x:870,y:390,q:130,known:false},{id:'thatch',type:'thatch',x:615,y:145,q:180,known:false}],leader:null,lastLeader:0,lastExperiment:0};linkTrust();running=false;selected=null;play.textContent='Start';render()}
init();
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),stamp=()=>`D${S.day} ${String(Math.floor(S.min/60)).padStart(2,'0')}:${String(Math.floor(S.min%60)).padStart(2,'0')}`;
function event(text,cls=''){S.events.unshift({t:stamp(),text,cls});S.events=S.events.slice(0,70)}function observe(text){S.observations.unshift(text);S.observations=S.observations.slice(0,15)}function memory(a,text){a.mem.unshift(text);a.mem=a.mem.slice(0,10)}function move(a,x,y,t){a.tx=x;a.ty=y;a.task=t}
function discover(a,r){if(!a.known[r.id]){a.known[r.id]=true;r.known=true;S.knowledge+=3;memory(a,`I discovered ${r.type}.`);event(`${a.name} discovered ${r.type}.`,'good');observe(`${a.name} privately knows a source of ${r.type}.`)}}
function known(a,type){return S.resources.filter(r=>a.known[r.id]&&r.type===type&&r.q>0).sort((p,q)=>dist(a,p)-dist(a,q))[0]}
function share(a,b){let ks=Object.keys(a.known).filter(k=>a.known[k]&&!b.known[k]);if(ks.length){let k=pick(ks),r=S.resources.find(x=>x.id===k);b.known[k]=true;memory(b,`${a.name} told me where ${r.type} can be found.`);S.knowledge+=.35}}
function speak(a,b){let lines=[];if(S.store.food<10)lines.push('Food is becoming dangerous to ignore.');if(S.store.water<10)lines.push('We need a safer water supply.');if(a.proposal)lines.push(`I want us to make ${a.proposal.name||BUILD[a.proposal]?.n}.`);if(S.traditions.length)lines.push(`The story of ${pick(S.traditions).name} matters to us.`);if(!lines.length)lines.push(pick(['This place could become our home.','We should make something our children can use.','Tell me what you have learned.','We cannot survive by each working alone.']));let l1=pick(lines),l2=pick(['I agree.','Show me.','The others should hear this.','I am not convinced yet.','Then help me do it.']);S.speech.unshift({t:stamp(),text:`${a.name}: “${l1}” — ${b.name}: “${l2}”`});S.speech=S.speech.slice(0,60);share(a,b);share(b,a);a.social=clamp(a.social-25);b.social=clamp(b.social-20);a.trust[b.id]=clamp(a.trust[b.id]+R(-1,4));b.trust[a.id]=clamp(b.trust[a.id]+R(-1,4));if(Math.random()<.08&&a.mem[0]){b.beliefs.unshift({text:a.mem[0],source:a.name,confidence:R(.55,.9)});b.beliefs=b.beliefs.slice(0,6)}}
function canPay(c){return Object.entries(c||{}).every(([k,v])=>(S.store[k]||0)>=v)}function pay(c){Object.entries(c||{}).forEach(([k,v])=>S.store[k]-=v)}
function idea(a){let base=Object.entries(BUILD).filter(([,b])=>(!b.k||S.tech[b.k])&&canPay(b.c));let custom=S.knowledge>70&&Math.random()<.28?pick(customIdeas.filter(x=>canPay(x.materials))):null;if(custom){a.proposal={...custom,custom:true};observe(`${a.name} conceived a new structure: ${custom.name}, to ${custom.purpose}.`);return}if(!base.length){a.proposal=null;return}let needFood=S.store.food<16,needHome=S.buildings.filter(b=>['housing','beds'].includes(b.benefit)).length<3,needWater=S.store.water<15;base=base.map(([k,b])=>({k,b,s:R(0,4)+(needHome&&['lean','hut'].includes(k)?8:0)+(needFood&&['rack','store','farm'].includes(k)?7:0)+(needWater&&k==='well'?7:0)+(a.role==='Builder'||a.role==='Maker'?2:0)})).sort((x,y)=>y.s-x.s);a.proposal=base[0].k}
function decide(a){if(a.thirst>76)return{a:'drink'};if(a.hunger>78)return{a:'eat'};if(a.fatigue>84)return{a:'sleep'};let w=known(a,'water'),f=known(a,'food'),wo=known(a,'wood'),st=known(a,'stone'),th=known(a,'thatch');if(S.store.water<11&&w)return{a:'gather',r:'water'};if(S.store.food<12&&f)return{a:'gather',r:'food'};if(S.store.wood<18&&wo)return{a:'gather',r:'wood'};if(S.store.thatch<12&&th&&S.tech.wattle)return{a:'gather',r:'thatch'};if(S.store.stone<10&&st&&S.knowledge>35)return{a:'gather',r:'stone'};if(a.role==='Healer'){let h=S.people.filter(x=>x.alive&&x.health<78).sort((x,y)=>x.health-y.health)[0];if(h)return{a:'heal',id:h.id}}if(a.social>62){let others=S.people.filter(x=>x.alive&&x.id!==a.id);if(others.length)return{a:'talk',id:pick(others).id}}if(!a.proposal||Math.random()<.18)idea(a);if(a.proposal&&(a.role==='Builder'||a.role==='Maker'||Math.random()<.25))return{a:'build',proposal:a.proposal};if(Math.random()<.48)return{a:'explore'};return{a:'gather',r:pick(['food','wood','water'])}}
function proposalData(p){if(typeof p==='string'){let b=BUILD[p];return{name:b.n,cost:b.c,benefit:b.b,w:b.w,h:b.h,kind:p}}return{name:p.name,cost:p.materials,benefit:p.benefit,w:R(26,48),h:R(20,38),kind:'custom',purpose:p.purpose,primitives:p.primitives}}
function site(kind){let ang=R(0,Math.PI*2),rad=kind==='farm'?R(130,185):kind==='wall'?R(175,210):R(72,155);return{x:clamp(S.camp.x+Math.cos(ang)*rad,80,925),y:clamp(S.camp.y+Math.sin(ang)*rad,70,630)}}
function action(a,d){if(d.a==='drink'){if(S.store.water>=1){S.store.water--;a.thirst=clamp(a.thirst-64);a.task='drinking';a.until=S.min+10}else action(a,{a:'explore'})}else if(d.a==='eat'){if(S.store.food>=1){S.store.food--;a.hunger=clamp(a.hunger-58);a.task='eating';a.until=S.min+15}else action(a,{a:'explore'})}else if(d.a==='sleep'){move(a,S.camp.x+R(-45,45),S.camp.y+R(-45,45),'sleeping');a.until=S.min+210}else if(d.a==='explore'){move(a,R(90,920),R(80,620),'exploring');a.until=S.min+90}else if(d.a==='talk'){let b=S.people.find(x=>x.id===d.id);if(b){a.target=b.id;move(a,b.x,b.y,`talking with ${b.name}`);a.until=S.min+24}}else if(d.a==='heal'){let b=S.people.find(x=>x.id===d.id);if(b){a.target=b.id;move(a,b.x,b.y,`healing ${b.name}`);a.until=S.min+35}}else if(d.a==='gather'){let r=known(a,d.r);if(!r){action(a,{a:'explore'});return}a.res=r.id;move(a,r.x+R(-12,12),r.y+R(-12,12),`gathering ${d.r}`)}else if(d.a==='build'){let P=proposalData(d.proposal);if(!P||!canPay(P.cost)){a.proposal=null;return}a.build=P;a.site=site(P.kind);move(a,a.site.x,a.site.y,`building ${P.name.toLowerCase()}`);a.until=S.min+90+Object.values(P.cost).reduce((s,v)=>s+v,0)*2}}
function arrival(a){for(const r of S.resources)if(dist(a,r)<75&&r.q>0)discover(a,r);if(a.res&&a.task.startsWith('gathering')){let r=S.resources.find(x=>x.id===a.res);if(r&&dist(a,r)<28){let q=r.type==='water'?4.5:3.5*a.skill.gather;if(r.q<9999){q=Math.min(q,r.q);r.q-=q}a.carry={type:r.type,q};move(a,S.camp.x+R(-25,25),S.camp.y+R(-25,25),`returning with ${r.type}`)}}else if(a.carry&&a.task.startsWith('returning')&&dist(a,S.camp)<58){S.store[a.carry.type]=(S.store[a.carry.type]||0)+a.carry.q;event(`${a.name} returned with ${a.carry.q.toFixed(1)} ${a.carry.type}.`,'good');a.carry=null;a.res=null;a.task='available'}}
function complete(a){if(a.task.startsWith('talking')&&a.target!=null){let b=S.people.find(x=>x.id===a.target);if(b&&b.alive)speak(a,b)}if(a.task.startsWith('healing')&&a.target!=null){let b=S.people.find(x=>x.id===a.target);if(b&&b.alive){b.health=clamp(b.health+16*a.skill.heal);b.trust[a.id]=clamp(b.trust[a.id]+6);memory(b,`${a.name} treated my injury.`)}}if(a.build){let p=a.build;if(canPay(p.cost)){pay(p.cost);S.buildings.push({id:S.nextBuilding++,kind:p.kind,n:p.name,b:p.benefit,x:a.site.x,y:a.site.y,w:p.w,h:p.h,by:a.name,day:S.day,purpose:p.purpose||'',primitives:p.primitives||[]});S.knowledge+=4*a.skill.build;event(`${a.name} completed ${p.name.toLowerCase()}.`,'good');if(p.kind==='custom')observe(`${p.name} entered the built tradition of the settlement; later builders can imitate it.`);memory(a,`I built ${p.name} on day ${S.day}.`)}a.build=null;a.site=null;a.proposal=null}if(a.task==='sleeping')a.fatigue=clamp(a.fatigue-58);a.until=0;a.target=null;a.task='available';a.cool=R(15,35)}
function experiment(){let alive=S.people.filter(x=>x.alive&&x.age>=12);if(!alive.length)return;let a=pick(alive.filter(x=>['Maker','Builder','Farmer','Cook'].includes(x.role)).length?alive.filter(x=>['Maker','Builder','Farmer','Cook'].includes(x.role)):alive);let candidates=EXPERIMENTS.filter(e=>!S.tech[e.id]&&e.needs.every(n=>(S.store[n]||0)>4));if(!candidates.length)return;let e=pick(candidates),chance=e.chance*a.skill.think*(1+Math.min(.7,S.knowledge/300));if(Math.random()<chance){S.tech[e.id]=true;S.knowledge+=10;event(`${a.name}'s experiments produced a new technique: ${e.name}.`,'violet');memory(a,`I discovered ${e.desc}.`);observe(`No tech-tree timer fired: ${e.name} emerged from ${a.name}'s experiment.`);if(e.id==='council')S.institutions.push({name:'Council circle',desc:'Adults gather to debate shared decisions.',day:S.day});if(e.id==='ritual'){let dead=S.people.filter(x=>!x.alive);let subject=dead.length?pick(dead).name:names[0];S.traditions.push({name:`Remembering ${subject}`,origin:`Stories about ${subject} are repeated at communal fires.`,day:S.day});S.institutions.push({name:'Ancestor remembrance',desc:'The dead are named in recurring communal gatherings.',day:S.day})}}else if(Math.random()<.3)observe(`${a.name} experimented with ${e.desc}, but the attempt did not work.`)}
function leadership(){let alive=S.people.filter(x=>x.alive);if(alive.length<2)return;let score=alive.map(a=>({a,s:alive.reduce((z,b)=>z+(b.id===a.id?0:(b.trust[a.id]||50)),0)/(alive.length-1)+(a.role==='Organizer'?7:0)})).sort((x,y)=>y.s-x.s)[0];if(score.s>63&&S.leader!==score.a.id){S.leader=score.a.id;event(`${score.a.name} emerged as the group's informal leader.`,'violet');observe('Leadership changed through accumulated trust rather than assignment.')}}
function demographics(){let adults=S.people.filter(x=>x.alive&&x.age>=18&&x.age<45),homes=S.buildings.filter(b=>b.b==='housing').length;if(S.day<45||homes<2||S.store.food<30||adults.length<2)return;if(Math.random()<.025){let p1=pick(adults),options=adults.filter(x=>x.id!==p1.id&&x.partner==null);if(options.length){let p2=pick(options);p1.partner=p2.id;p2.partner=p1.id;observe(`${p1.name} and ${p2.name} formed a household.`)}}let pairs=adults.filter(a=>a.partner!=null&&a.id<a.partner);if(pairs.length&&Math.random()<.018&&S.people.filter(x=>x.alive).length<26){let p1=pick(pairs),p2=S.people.find(x=>x.id===p1.partner),id=S.nextPerson++,child=person(id,`Child ${id-11}`);child.age=0;child.role='Child';child.parents=[p1.id,p2.id];child.x=S.camp.x+R(-30,30);child.y=S.camp.y+R(-30,30);p1.children.push(id);p2.children.push(id);S.people.push(child);linkTrust();event(`${child.name} was born to ${p1.name} and ${p2.name}.`,'good');observe('A person has now been born who never experienced the founding migration. Culture must be inherited, not remembered firsthand.')}}
function nextDay(){S.weather=Math.random()<.15?'Rain':Math.random()<.08?'Cold snap':'Clear';if(S.weather==='Rain')S.store.water+=5;let farms=S.buildings.filter(b=>b.b==='farm').length,fish=S.buildings.filter(b=>b.b==='fish').length,stores=S.buildings.filter(b=>b.b==='storage').length,preserve=S.buildings.filter(b=>b.b==='preserve').length;if(farms)S.store.food+=farms*4;if(fish)S.store.food+=fish*2.5;S.store.food*=Math.max(.87,.93+stores*.012+preserve*.012);if(Math.random()<.1){let a=pick(S.people.filter(x=>x.alive));if(a){a.health-=R(8,22);event(`${a.name} was injured during daily work.`,'warn')}}for(const a of S.people)if(S.day%120===0)a.age++;demographics();if(S.day%2===0)experiment();}
function tick(dt){S.min+=dt;if(S.min>=1440){S.min-=1440;S.day++;nextDay()}let hr=S.min/60;S.temp=60+14*Math.sin((hr-7)/24*Math.PI*2)+(S.weather==='Cold snap'?-14:S.weather==='Rain'?-4:0);for(const a of S.people){if(!a.alive)continue;a.hunger=clamp(a.hunger+dt*.03);a.thirst=clamp(a.thirst+dt*.045);a.fatigue=clamp(a.fatigue+dt*.025);a.social=clamp(a.social+dt*.012);if(a.task==='sleeping')a.fatigue=clamp(a.fatigue-dt*.1);if(a.hunger>92)a.health-=dt*.02;if(a.thirst>92)a.health-=dt*.05;let dx=a.tx-a.x,dy=a.ty-a.y,d=Math.hypot(dx,dy);if(d>3){let s=Math.min(d,dt*1.8);a.x+=dx/d*s;a.y+=dy/d*s}else arrival(a);if(a.until&&S.min>=a.until)complete(a);if(a.health<=0){a.alive=false;a.task='dead';event(`${a.name} died.`,'bad');for(const b of S.people)if(b.alive)memory(b,`${a.name} died on day ${S.day}.`);if(!S.tech.ritual&&Math.random()<.3)observe(`Repeated memories of ${a.name} may eventually become a communal tradition.`)}a.cool-=dt;if(a.cool<=0&&!a.res&&!a.carry&&(!a.until||a.task==='available')){action(a,decide(a));a.cool=R(18,42)}}S.knowledge+=dt*.004*S.people.filter(x=>x.alive&&x.age>=10).length;if(S.min-S.lastLeader>180||S.min<S.lastLeader){leadership();S.lastLeader=S.min}}
function era(){let b=S.buildings.length,t=Object.keys(S.tech).length;if(t>=9&&b>=14)return['Fortified village','Multiple generations now live among specialized buildings, institutions and defenses.'];if(t>=7&&b>=10)return['Organized village','Specialists, communal institutions and shared traditions structure daily life.'];if(t>=5&&b>=6)return['Permanent settlement','Food production, durable homes and storage are tying families to this place.'];if(b>=2)return['Base camp','Repeated building and shared knowledge are turning a stopping place into a settlement.'];return['Wandering band','They know fire and stone tools. Everything else must emerge through survival, experiment and teaching.']}
function resize(){let r=C.parentElement.getBoundingClientRect(),d=devicePixelRatio||1;C.width=r.width*d;C.height=r.height*d;C.style.width=r.width+'px';C.style.height=r.height+'px';X.setTransform(d,0,0,d,0,0);W=r.width;H=r.height}addEventListener('resize',resize);resize();const sx=x=>x/1000*W,sy=y=>y/700*H;
function draw(){X.clearRect(0,0,W,H);X.fillStyle='#171b12';X.fillRect(0,0,W,H);X.strokeStyle='#202619';for(let x=0;x<W;x+=44){X.beginPath();X.moveTo(x,0);X.lineTo(x,H);X.stroke()}for(let y=0;y<H;y+=44){X.beginPath();X.moveTo(0,y);X.lineTo(W,y);X.stroke()}X.strokeStyle='#315b67';X.lineWidth=Math.max(22,W*.035);X.beginPath();X.moveTo(sx(60),sy(65));X.bezierCurveTo(sx(180),sy(230),sx(85),sy(450),sx(175),sy(665));X.stroke();for(const r of S.resources){X.globalAlpha=r.known?.9:.18;X.fillStyle=r.type==='water'?'#75a6b8':r.type==='food'?'#8cad6f':r.type==='wood'?'#8b684c':r.type==='stone'?'#909287':'#b2a36e';X.beginPath();X.arc(sx(r.x),sy(r.y),7,0,7);X.fill();X.globalAlpha=1}X.strokeStyle='#554d39';X.lineWidth=1;for(const b of S.buildings){X.beginPath();X.moveTo(sx(S.camp.x),sy(S.camp.y));X.lineTo(sx(b.x),sy(b.y));X.stroke()}for(const b of S.buildings){let x=sx(b.x),y=sy(b.y),w=Math.max(12,b.w/1000*W),h=Math.max(9,b.h/700*H);X.fillStyle=b.b==='farm'?'#6d6b39':b.kind==='custom'?'#776449':'#6f5a43';X.fillRect(x-w/2,y-h/2,w,h);X.strokeStyle='#ad9975';X.strokeRect(x-w/2,y-h/2,w,h)}for(const a of S.people){let x=sx(a.x),y=sy(a.y);if(!a.alive){X.fillStyle='#55584e';X.fillRect(x-6,y,12,2);continue}if(a.id===selected){X.strokeStyle='#eeeadd';X.beginPath();X.arc(x,y,11,0,7);X.stroke()}if(S.leader===a.id){X.strokeStyle='#ad9bd7';X.beginPath();X.arc(x,y,15,0,7);X.stroke()}X.fillStyle=a.age<10?'#d7b48e':'#c08b63';X.beginPath();X.arc(x,y,a.age<10?4:6,0,7);X.fill();X.fillStyle='#eeeadd';X.textAlign='center';X.font='10px system-ui';X.fillText(a.name,x,y-10)}}
function renderFeed(){let f=document.getElementById('feed');if(tab==='history')f.innerHTML=S.events.slice(0,17).map(e=>`<div class="item ${e.cls}"><span class="time">${e.t}</span> · ${e.text}</div>`).join('');else if(tab==='speech')f.innerHTML=S.speech.slice(0,15).map(e=>`<div class="item"><span class="time">${e.t}</span><br>${e.text}</div>`).join('')||'<div class="small">No recorded speech yet.</div>';else f.innerHTML=S.buildings.slice().reverse().map(b=>`<div class="item"><b>${b.n}</b><div class="small">${b.purpose||b.b} · ${b.by} · Day ${b.day}</div></div>`).join('')||'<div class="small">No permanent structures yet.</div>'}
function render(){let alive=S.people.filter(x=>x.alive);pop.textContent=alive.length;food.textContent=Math.round(S.store.food);water.textContent=Math.round(S.store.water);wood.textContent=Math.round(S.store.wood);stone.textContent=Math.round(S.store.stone);know.textContent=Math.round(S.knowledge);let h=Math.floor(S.min/60),m=Math.floor(S.min%60);clockText.textContent=`Day ${S.day} · ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;weather.textContent=`${S.weather} · ${Math.round(S.temp)}°F`;let e=era();eraTitle.textContent=e[0];eraText.textContent=e[1];status.textContent=`${e[0]} · ${alive.length} people · ${S.buildings.length} structures · ${Object.keys(S.tech).length} techniques`;agents.innerHTML=S.people.map(a=>`<div class="agent ${a.id===selected?'active':''}" data-id="${a.id}"><div class="row"><span class="dot ${a.alive?'':'dead'}"></span><b class="grow">${a.name}${S.leader===a.id?' ★':''}</b><span class="small">${a.role}</span></div><div class="small">${a.alive?a.task:'deceased'} · age ${a.age}</div></div>`).join('');document.querySelectorAll('.agent').forEach(el=>el.onclick=()=>{selected=+el.dataset.id;render()});observations.innerHTML=S.observations.map(x=>`<div class="obs">${x}</div>`).join('');institutions.innerHTML=[...S.institutions.map(i=>`<div class="institution"><b>${i.name}</b><div class="small">${i.desc} · Day ${i.day}</div></div>`),...S.traditions.map(t=>`<div class="institution"><b>${t.name}</b><div class="small">Oral tradition · ${t.origin}</div></div>`)].join('')||'<div class="small">No formal institutions or named traditions yet.</div>';renderFeed();if(selected==null){detail.innerHTML='<span class="small">Select someone.</span>';return}let a=S.people.find(x=>x.id===selected),bar=(l,v,inv=false)=>`<div class="barlabel"><span>${l}</span><span>${Math.round(v)}</span></div><div class="bar"><div class="fill" style="width:${clamp(v)}%;background:${inv&&v>75?'#d97967':'#96bd78'}"></div></div>`,parentNames=a.parents.map(id=>S.people.find(x=>x.id===id)?.name).filter(Boolean).join(' + ');detail.innerHTML=`<div style="font-size:18px;font-weight:800">${a.name}${S.leader===a.id?' ★':''}</div><div class="small">${a.role} · ${a.trait} · age ${a.age}</div><div><span class="tag">${a.task}</span>${a.proposal?`<span class="tag">idea: ${typeof a.proposal==='string'?BUILD[a.proposal].n:a.proposal.name}</span>`:''}</div>${bar('Health',a.health)}${bar('Morale',a.morale)}${bar('Hunger',a.hunger,true)}${bar('Thirst',a.thirst,true)}${bar('Fatigue',a.fatigue,true)}<h3 style="margin-top:12px">Life</h3><div class="item">Goal: ${a.goal}${parentNames?`<br>Parents: ${parentNames}`:''}${a.partner!=null?`<br>Partner: ${S.people.find(x=>x.id===a.partner)?.name}`:''}</div><h3 style="margin-top:10px">Memories & beliefs</h3>${a.mem.slice(0,6).map(m=>`<div class="item">${m}</div>`).join('')}${a.beliefs.map(b=>`<div class="item"><span class="violet">Heard from ${b.source}</span>: ${b.text}</div>`).join('')}`}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));renderFeed()});play.onclick=()=>{running=!running;play.textContent=running?'Pause':'Start'};document.getElementById('speed').onchange=e=>speed=+e.target.value;reset.onclick=()=>{localStorage.removeItem('first-village-save');init()};save.onclick=()=>{localStorage.setItem('first-village-save',JSON.stringify(S));event('Village saved in this browser.','good');render()};C.onclick=e=>{let r=C.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,a=S.people.filter(x=>x.alive).sort((p,q)=>Math.hypot(sx(p.x)-mx,sy(p.y)-my)-Math.hypot(sx(q.x)-mx,sy(q.y)-my))[0];if(a&&Math.hypot(sx(a.x)-mx,sy(a.y)-my)<24){selected=a.id;render()}};try{let z=localStorage.getItem('first-village-save');if(z){S=JSON.parse(z);linkTrust();event('Saved village restored.','good')}}catch(e){}
function loop(n){let dt=Math.min(.05,(n-last)/1000);last=n;if(running){acc+=dt*speed;while(acc>.055){tick(1.25);acc-=.055}}draw();if(n%(running?180:500)<18)render();requestAnimationFrame(loop)}requestAnimationFrame(loop);