const C=document.getElementById('world'),X=C.getContext('2d');
let W=1000,H=700,running=false,speed=1,last=performance.now(),acc=0,selected=null;
const R=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.floor(Math.random()*a.length)],clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const names=['Mara','Eli','June','Caleb','Nora','Theo','Iris','Jonah','Mae','Rowan','Ada','Silas'];
const roles=['Forager','Maker','Healer','Scout','Cook','Gatherer','Farmer','Builder','Healer','Hunter','Maker','Organizer'];
const traits=['cooperative','cautious','empathetic','bold','practical','curious','stubborn','calm','social','competitive','inventive','organized'];
const BUILD={hearth:{n:'Hearth',c:{wood:3,stone:4},b:'fire'},lean:{n:'Lean-to',c:{wood:8},b:'beds'},rack:{n:'Drying rack',c:{wood:7},b:'preserve'},hut:{n:'Wattle hut',c:{wood:16},b:'housing',k:40},store:{n:'Storehouse',c:{wood:20,stone:5},b:'storage',k:65},farm:{n:'Field',c:{wood:5},b:'farm',k:90},well:{n:'Lined well',c:{wood:8,stone:18},b:'well',k:125},shop:{n:'Workshop',c:{wood:18,stone:10},b:'craft',k:165},hall:{n:'Meeting hall',c:{wood:30,stone:14},b:'governance',k:210},wall:{n:'Palisade',c:{wood:24},b:'defense',k:290}};
let S;
function person(i){return{id:i,name:names[i],role:roles[i],trait:traits[i],x:510+R(-45,45),y:350+R(-40,40),tx:510,ty:350,health:100,hunger:R(5,15),thirst:R(4,13),fatigue:R(5,18),morale:R(68,90),task:'looking around',until:0,cool:R(0,15),res:null,proposal:null,known:{river:false,food:false,wood:false,stone:false,game:false},mem:['We entered this valley together.'],trust:Object.fromEntries(names.map((_,j)=>[j,j===i?100:R(45,68)]))}}
function init(){S={day:1,min:420,temp:71,weather:'Clear',store:{food:13,water:15,wood:8,stone:2},knowledge:0,camp:{x:510,y:350},people:Array.from({length:12},(_,i)=>person(i)),buildings:[],events:[{t:'D1 07:00',text:'Twelve hunter-gatherers enter an unfamiliar valley.',cls:''}],resources:[{id:'river',type:'water',x:155,y:170,q:9999,known:false},{id:'food',type:'food',x:800,y:170,q:110,known:false},{id:'wood',type:'wood',x:230,y:555,q:260,known:false},{id:'stone',type:'stone',x:760,y:555,q:240,known:false},{id:'game',type:'food',x:870,y:390,q:130,known:false}]};running=false;selected=null;play.textContent='Start';render()}
init();
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),stamp=()=>`D${S.day} ${String(Math.floor(S.min/60)).padStart(2,'0')}:${String(Math.floor(S.min%60)).padStart(2,'0')}`;
function event(text,cls=''){S.events.unshift({t:stamp(),text,cls});S.events=S.events.slice(0,50)}
function move(a,x,y,t){a.tx=x;a.ty=y;a.task=t}
function discover(a,r){if(!a.known[r.id]){a.known[r.id]=true;r.known=true;S.knowledge+=3;a.mem.unshift(`I discovered ${r.type}.`);event(`${a.name} discovered ${r.type}.`,'good')}}
function known(a,type){return S.resources.filter(r=>a.known[r.id]&&r.type===type&&r.q>0).sort((p,q)=>dist(a,p)-dist(a,q))[0]}
function canPay(c){return Object.entries(c).every(([k,v])=>(S.store[k]||0)>=v)}
function pay(c){Object.entries(c).forEach(([k,v])=>S.store[k]-=v)}
function chooseBuilding(a){let opts=Object.entries(BUILD).filter(([,b])=>(!b.k||S.knowledge>=b.k)&&canPay(b.c));if(!opts.length)return null;let needFood=S.store.food<15,needWater=S.store.water<15,needHome=S.buildings.filter(b=>b.b==='housing'||b.b==='beds').length<3;let scored=opts.map(([k,b])=>({k,s:R(0,4)+(needHome&&(k==='lean'||k==='hut')?8:0)+(needFood&&(k==='rack'||k==='farm'||k==='store')?7:0)+(needWater&&k==='well'?8:0)+(a.role==='Builder'||a.role==='Maker'?2:0)})).sort((x,y)=>y.s-x.s);return scored[0].k}
function decide(a){if(a.thirst>76)return{a:'drink'};if(a.hunger>78)return{a:'eat'};if(a.fatigue>84)return{a:'sleep'};let w=known(a,'water'),f=known(a,'food'),wo=known(a,'wood'),st=known(a,'stone');if(S.store.water<11&&w)return{a:'gather',r:'water'};if(S.store.food<12&&f)return{a:'gather',r:'food'};if(S.store.wood<18&&wo)return{a:'gather',r:'wood'};if(S.store.stone<10&&st&&S.knowledge>50)return{a:'gather',r:'stone'};let b=chooseBuilding(a);if(b&&(a.role==='Builder'||a.role==='Maker'||Math.random()<.25))return{a:'build',k:b};if(Math.random()<.5)return{a:'explore'};return{a:'gather',r:pick(['food','wood','water'])}}
function action(a,d){if(d.a==='drink'){if(S.store.water){S.store.water--;a.thirst=clamp(a.thirst-64);a.task='drinking';a.until=S.min+10}else action(a,{a:'explore'})}else if(d.a==='eat'){if(S.store.food){S.store.food--;a.hunger=clamp(a.hunger-58);a.task='eating';a.until=S.min+15}else action(a,{a:'explore'})}else if(d.a==='sleep'){move(a,S.camp.x+R(-45,45),S.camp.y+R(-45,45),'sleeping');a.until=S.min+210}else if(d.a==='explore'){move(a,R(90,920),R(80,620),'exploring');a.until=S.min+90}else if(d.a==='gather'){let r=known(a,d.r);if(!r){action(a,{a:'explore'});return}a.res=r.id;move(a,r.x+R(-12,12),r.y+R(-12,12),`gathering ${d.r}`)}else if(d.a==='build'){let b=BUILD[d.k];if(!b||!canPay(b.c))return;let ang=R(0,Math.PI*2),rad=d.k==='farm'?145:R(75,150);a.site={x:S.camp.x+Math.cos(ang)*rad,y:S.camp.y+Math.sin(ang)*rad};a.build=d.k;move(a,a.site.x,a.site.y,`building ${b.n.toLowerCase()}`);a.until=S.min+90+Object.values(b.c).reduce((s,v)=>s+v,0)*2}}
function arrival(a){for(const r of S.resources)if(dist(a,r)<75&&r.q>0)discover(a,r);if(a.res&&a.task.startsWith('gathering')){let r=S.resources.find(x=>x.id===a.res);if(r&&dist(a,r)<28){let q=r.type==='water'?4.5:3.5;if(r.q<9999){q=Math.min(q,r.q);r.q-=q}a.carry={type:r.type,q};move(a,S.camp.x+R(-25,25),S.camp.y+R(-25,25),`returning with ${r.type}`)}}else if(a.carry&&a.task.startsWith('returning')&&dist(a,S.camp)<58){S.store[a.carry.type]+=a.carry.q;event(`${a.name} returned with ${a.carry.q.toFixed(1)} ${a.carry.type}.`,'good');a.carry=null;a.res=null;a.task='available'}}
function complete(a){if(a.build){let b=BUILD[a.build];if(canPay(b.c)){pay(b.c);S.buildings.push({kind:a.build,n:b.n,b:b.b,x:a.site.x,y:a.site.y,by:a.name,day:S.day});S.knowledge+=4;event(`${a.name} completed a ${b.n.toLowerCase()}.`,'good')}a.build=null;a.site=null}if(a.task==='sleeping')a.fatigue=clamp(a.fatigue-58);a.until=0;a.task='available';a.cool=R(15,35)}
function nextDay(){S.weather=Math.random()<.15?'Rain':Math.random()<.08?'Cold snap':'Clear';if(S.weather==='Rain')S.store.water+=5;let farms=S.buildings.filter(b=>b.b==='farm').length,stores=S.buildings.filter(b=>b.b==='storage').length,racks=S.buildings.filter(b=>b.b==='preserve').length;if(farms){let q=farms*4;S.store.food+=q;event(`Managed fields yielded ${q} food.`,'good')}S.store.food*=Math.max(.88,.93+stores*.01+racks*.01)}
function tick(dt){S.min+=dt;if(S.min>=1440){S.min-=1440;S.day++;nextDay()}let hr=S.min/60;S.temp=60+14*Math.sin((hr-7)/24*Math.PI*2)+(S.weather==='Cold snap'?-14:S.weather==='Rain'?-4:0);for(const a of S.people){a.hunger=clamp(a.hunger+dt*.03);a.thirst=clamp(a.thirst+dt*.045);a.fatigue=clamp(a.fatigue+dt*.025);if(a.task==='sleeping')a.fatigue=clamp(a.fatigue-dt*.1);if(a.hunger>92)a.health-=dt*.02;if(a.thirst>92)a.health-=dt*.05;let dx=a.tx-a.x,dy=a.ty-a.y,d=Math.hypot(dx,dy);if(d>3){let s=Math.min(d,dt*1.8);a.x+=dx/d*s;a.y+=dy/d*s}else arrival(a);if(a.until&&S.min>=a.until)complete(a);a.cool-=dt;if(a.cool<=0&&!a.res&&!a.carry&&(!a.until||a.task==='available')){action(a,decide(a));a.cool=R(18,42)}}S.knowledge+=dt*.006*S.people.length}
function era(){if(S.knowledge>=290&&S.buildings.length>=12)return['Fortified village','Permanent architecture, fields, specialists and defenses now define the settlement.'];if(S.knowledge>=165&&S.buildings.length>=8)return['Organized village','Specialized work and durable communal buildings are emerging.'];if(S.knowledge>=90&&S.buildings.length>=5)return['Permanent settlement','Cultivation and repeated construction are tying people to place.'];if(S.buildings.length>=2)return['Base camp','The band has begun turning repeated use of this place into a village.'];return['Wandering band','They know fire and stone tools. Everything else must emerge through survival and discovery.']}
function resize(){let r=C.parentElement.getBoundingClientRect(),d=devicePixelRatio||1;C.width=r.width*d;C.height=r.height*d;C.style.width=r.width+'px';C.style.height=r.height+'px';X.setTransform(d,0,0,d,0,0);W=r.width;H=r.height}addEventListener('resize',resize);resize();const sx=x=>x/1000*W,sy=y=>y/700*H;
function draw(){X.clearRect(0,0,W,H);X.fillStyle='#171b12';X.fillRect(0,0,W,H);X.strokeStyle='#315b67';X.lineWidth=Math.max(22,W*.035);X.beginPath();X.moveTo(sx(60),sy(65));X.bezierCurveTo(sx(180),sy(230),sx(85),sy(450),sx(175),sy(665));X.stroke();for(const r of S.resources){X.globalAlpha=r.known?.9:.18;X.fillStyle=r.type==='water'?'#75a6b8':r.type==='food'?'#8cad6f':r.type==='wood'?'#8b684c':'#909287';X.beginPath();X.arc(sx(r.x),sy(r.y),7,0,7);X.fill();X.globalAlpha=1}for(const b of S.buildings){X.fillStyle=b.b==='farm'?'#6d6b39':'#6f5a43';let w=b.b==='farm'?50:28,h=b.b==='farm'?38:22;X.fillRect(sx(b.x)-w/2,sy(b.y)-h/2,w,h)}for(const a of S.people){let x=sx(a.x),y=sy(a.y);if(a.id===selected){X.strokeStyle='#eeeadd';X.beginPath();X.arc(x,y,11,0,7);X.stroke()}X.fillStyle='#c08b63';X.beginPath();X.arc(x,y,6,0,7);X.fill();X.fillStyle='#eeeadd';X.textAlign='center';X.font='10px system-ui';X.fillText(a.name,x,y-10)}}
function render(){pop.textContent=S.people.length;food.textContent=Math.round(S.store.food);water.textContent=Math.round(S.store.water);wood.textContent=Math.round(S.store.wood);stone.textContent=Math.round(S.store.stone);know.textContent=Math.round(S.knowledge);let h=Math.floor(S.min/60),m=Math.floor(S.min%60);clockText.textContent=`Day ${S.day} · ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;weather.textContent=`${S.weather} · ${Math.round(S.temp)}°F`;let e=era();eraTitle.textContent=e[0];eraText.textContent=e[1];status.textContent=`${e[0]} · ${S.buildings.length} structures · Day ${S.day}`;agents.innerHTML=S.people.map(a=>`<div class="agent ${a.id===selected?'active':''}" data-id="${a.id}"><div class="row"><span class="dot"></span><b class="grow">${a.name}</b><span class="small">${a.role}</span></div><div class="small">${a.task}</div></div>`).join('');document.querySelectorAll('.agent').forEach(el=>el.onclick=()=>{selected=+el.dataset.id;render()});events.innerHTML=S.events.slice(0,16).map(e=>`<div class="item ${e.cls}"><span class="time">${e.t}</span> · ${e.text}</div>`).join('');buildings.innerHTML=S.buildings.slice().reverse().map(b=>`<div class="item"><b>${b.n}</b><div class="small">Built by ${b.by} · Day ${b.day}</div></div>`).join('')||'<div class="small">No permanent structures yet.</div>';if(selected==null){detail.innerHTML='<span class="small">Select someone.</span>';return}let a=S.people[selected],bar=(l,v,inv=false)=>`<div class="barlabel"><span>${l}</span><span>${Math.round(v)}</span></div><div class="bar"><div class="fill" style="width:${clamp(v)}%;background:${inv&&v>75?'#d97967':'#96bd78'}"></div></div>`;detail.innerHTML=`<div style="font-size:18px;font-weight:800">${a.name}</div><div class="small">${a.role} · ${a.trait}</div><div><span class="tag">${a.task}</span></div>${bar('Health',a.health)}${bar('Hunger',a.hunger,true)}${bar('Thirst',a.thirst,true)}${bar('Fatigue',a.fatigue,true)}<h3 style="margin-top:12px">Memories</h3>${a.mem.map(m=>`<div class="item">${m}</div>`).join('')}`}
play.onclick=()=>{running=!running;play.textContent=running?'Pause':'Start'};document.getElementById('speed').onchange=e=>speed=+e.target.value;reset.onclick=init;C.onclick=e=>{let r=C.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,a=S.people.sort((p,q)=>Math.hypot(sx(p.x)-mx,sy(p.y)-my)-Math.hypot(sx(q.x)-mx,sy(q.y)-my))[0];if(a&&Math.hypot(sx(a.x)-mx,sy(a.y)-my)<24){selected=a.id;render()}};
function loop(n){let dt=Math.min(.05,(n-last)/1000);last=n;if(running){acc+=dt*speed;while(acc>.055){tick(1.25);acc-=.055}}draw();if(n%(running?180:500)<18)render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
